In [4]:
import requests
import pandas as pd
import json
def coleta_nomes_cidades():

    url_ibge = 'https://servicodados.ibge.gov.br/api/v1/localidades/municipios'
    lista_municipios = []
    r = requests.get(url_ibge)
    if r.status_code == 200:
        lista = r.json()
    else:
        print(f"Erro na requisição: {r.status_code}")
    try:
        for posicao in lista:
            lista_municipios.append({'Cidade' : posicao['nome'],'Estado' : posicao['microrregiao']['mesorregiao']['UF']['nome']})
        return lista_municipios
    except(TypeError):
        print( f'Erro: {TypeError}')
    return lista_municipios

In [ ]:
enderecos = coleta_nomes_cidades()

Erro: <class 'TypeError'>

                     Cidade       Estado
0     Alta Floresta D'Oeste     Rondônia
1                 Ariquemes     Rondônia
2                    Cabixi     Rondônia
3                    Cacoal     Rondônia
4                Cerejeiras     Rondônia
...                     ...          ...
5194             Arenápolis  Mato Grosso
5195               Aripuanã  Mato Grosso
5196       Barão de Melgaço  Mato Grosso
5197        Barra do Bugres  Mato Grosso
5198        Barra do Garças  Mato Grosso

[5199 rows x 2 columns]

In [10]:
enderecos = pd.DataFrame(enderecos)
enderecos

                     Cidade       Estado
0     Alta Floresta D'Oeste     Rondônia
1                 Ariquemes     Rondônia
2                    Cabixi     Rondônia
3                    Cacoal     Rondônia
4                Cerejeiras     Rondônia
...                     ...          ...
5194             Arenápolis  Mato Grosso
5195               Aripuanã  Mato Grosso
5196       Barão de Melgaço  Mato Grosso
5197        Barra do Bugres  Mato Grosso
5198        Barra do Garças  Mato Grosso

[5199 rows x 2 columns]

In [15]:
from geopy.geocoders import Nominatim
def obter_lat_lon(endereco):
    geolocator = Nominatim(user_agent="meu_app")
    localizacao = geolocator.geocode(endereco)
    return localizacao.latitude, localizacao.longitude

In [18]:
# Supondo que obter_lat_lon(retorne uma tupla (lat, lon))
enderecos[['lat', 'lon']] = enderecos.apply(
    lambda row: obter_lat_lon(f"{row['Cidade']}, {row['Estado']}, Brasil"),
    axis=1, result_type='expand'
)

GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Espig%C3%A3o+D%27Oeste%2C+Rond%C3%B4nia%2C+Brasil&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

In [19]:
enderecos

                     Cidade       Estado
0     Alta Floresta D'Oeste     Rondônia
1                 Ariquemes     Rondônia
2                    Cabixi     Rondônia
3                    Cacoal     Rondônia
4                Cerejeiras     Rondônia
...                     ...          ...
5194             Arenápolis  Mato Grosso
5195               Aripuanã  Mato Grosso
5196       Barão de Melgaço  Mato Grosso
5197        Barra do Bugres  Mato Grosso
5198        Barra do Garças  Mato Grosso

[5199 rows x 2 columns]

In [14]:
from geopy.geocoders import Nominatim

geolocator = Nominatim(user_agent="meu_app")

# Nome do município, estado e país
municipio = "Uberlândia, Minas Gerais, Brasil"

localizacao = geolocator.geocode(municipio)

if localizacao:
    print(f"Latitude: {localizacao.latitude}")
    print(f"Longitude: {localizacao.longitude}")
else:
    print("Local não encontrado.")

Latitude: -18.9188041
Longitude: -48.2767837